### ISSUE TITLE
custom_components.spook.ectoplasms.homeassistant.sensor.HomeAssistantSpookSensorEntity

### ISSUE THREAD

**Issue by cdouet** [frenck/spook#262]
Hello,

I get the following warning on home assistant at start up:
_Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1004
First occurred: 7:30:33 AM (1 occurrences)
Last logged: 7:30:33 AM

Entity sensor.custom_integrations (<class 'custom_components.spook.ectoplasms.homeassistant.sensor.HomeAssistantSpookSensorEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author._

My system config is as follow:
Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

Can you please advise how to mitigate this?

Thanks in advance

**Comment by frenck** [comment]
This was fixed in #233

**Comment by cdouet** [comment]
Hi Frenck,

I am on 0.14.0 and I still have this warning message on my home assistant startup log... So I believe it is not completely fixed...

By the way, thanks for the great stuffs

**Comment by frenck** [comment]
It is fixed on dev, not released yet.

**Comment by cdouet** [comment]
👌

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
