### ISSUE TITLE
Repair refresh rate?

### ISSUE THREAD

**Issue by Anto79-ops** [frenck/spook#620]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2024.2.x

### The problem

Good day,

I don't know if this is an issue or a new feature but I wanted to mention it.

I just recently updated from version 2.2.0 to 2.2.2 and I noticed a change in how spook works.

For example on every restart of Home assistant, I always get two repair notifications one involving a previous issue that I submitted with Google Drive backup ( still hasn't been repaired but basically the entity becomes available after a minute or two) and one involving the entities on my dashboard which are empty on Startup and are related to my vehicle.

Typically what happens to both these repairs is that the eventually disappear on their own for example the Google Drive backup disappears after about 2 minutes from home assistant startup and the vehicle one disappears after about 2 minutes from driving my vehicle. However with the new Spook version, the repairs do not disappear, and they stay there, and I have to manually ignore them, even though the entities that it complains that are missing are actually there.

I'm just curious if this is something that has been newly implemented in spook or if there is an issue. Thank you

**Comment by MrFr33man123** [comment]
+1 with the new version it seems to only run one time after startup. The already fixed stuff from yesterday is still there. Before it was almost immediately resolved.
Reloading the Integration just makes all entities unavailable. Spook is so awesome and a good integration to take care of things that would go missed otherwise i love it.
Restarting HA is no solution. Maybe someone can debug.
I run HA 2024.2.1 in a docker container.
Spook is latest version v2.2.2

**Comment by DarwinData** [comment]
I have a similar problem in that if I get a repair notification and I fix the problem, then in most cases the repair notification will disappear on its own, but sometimes it will not clear, even though the issue is fixed, until the next restart and then it clears.
BTW, this is a great improvement to HA.  It found many small issues with entities in dashboards and automations.
Thanks!

**Comment by Anto79-ops** [comment]
now a weird thing happend...those 2 repairs that I speak of, which are always there on any restart, now do not show up at all.

sorry not sure how else to describe it, from being persistent to missing.

**Comment by Anto79-ops** [comment]
Turns those repairs were there but ignored permanently. 

Had 2 new repairs come up,  but they did not clear themselves when they were corrected.

**Comment by Ascathon** [comment]
Maybe not exactly related but that would solve my "unavailable service" error in an automation. After reboot the Android TV Remote integration does not load because the TV is turned off at that moment. Resulting in those entities becoming unavailable.
But meanwhile the TV has been turned on and the integration reloaded itself.
But the error still showing a related servicebeing unavailable, which it isn't.

**Comment by frenck** [comment]
I've deduplicated and generalized the cleanup of issues in #603, so this might be a regression of that.

Will take a look as soon as my spare time allows that.

../Frenck

**Comment by AlexKusnezov** [comment]
> Turns those repairs were there but ignored permanently.
> 
> Had 2 new repairs come up, but they did not clear themselves when they were corrected.

same here, I'm having a repair issue for a sensor group, which I've corrected, then deleted, deleted statistics, recreated several times but the issue won't clear itself until I... restart HA. I guess?
Also spook integration can't reloaded resulting in unavailable entities, maybe total unrelated. I think spook is not even a homie to himself ;)

**Comment by dtpugh** [comment]
I am noticing the same. 

BTW this one of my favorite addons - thanks. So useful should be part of the core.

Seems to detect an issue within seconds, then doesn't clear once fixed until you perform a full restart. Is there a way of restarting spook without a full restart of HA?

Easy to replicate, just change something incorrectly in dashboard YAML, let Spook find it and then fix.

**Comment by derailius** [comment]
> I am noticing the same.
> 
> BTW this one of my favorite addons - thanks. So useful should be part of the core.
> 
> Seems to detect an issue within seconds, then doesn't clear once fixed until you perform a full restart. Is there a way of restarting spook without a full restart of HA?
> 
> Easy to replicate, just change something incorrectly in dashboard YAML, let Spook find it and then fix.

I am having the same issue. 

Home Assistant
Core
2024.2.4
Supervisor
2024.02.0
Frontend
20240207.1

repaired issues remain until a reboot.

**Comment by Anto79-ops** [comment]
Thanks! the latest version has solved the problem.

**Comment by frenck** [comment]
Awesome! Thanks for letting me know @Anto79-ops ❤️ 

../Frenck
