### ISSUE TITLE
Validation of translation placeholders for localized (da) string component.spook.issues.script_unknown_device_references.description failed

### ISSUE THREAD

**Issue by jascdk** [frenck/spook#631]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2024.2

### The problem

I get the following error in logs at HA startup:

Validation of translation placeholders for localized (da) string component.spook.issues.script_unknown_device_references.description failed

HA language is set to english, but I live in Denmark.

Many thanks for the fantastic work on Spook and HA!

### Anything in the logs? Paste it here!

```plain text
Validation of translation placeholders for localized (da) string component.spook.issues.script_unknown_device_references.description failed
```

**Comment by jascdk** [comment]
Any fix?

**Comment by frenck** [comment]
Fixed by https://github.com/frenck/spook/pull/614/commits/d29a7ff5153cb9a6aa0dcc712117571088713d33

Will be part of the next release.

../Frenck

**Comment by jascdk** [comment]
hi @frenck 

I still encounter problems: 

My logs says

```
Logger: homeassistant.helpers.translation
Kilde: helpers/translation.py:285 
Første forekomst: 16.47.59 (1 forekomster) 
Senest logget: 16.47.59

Validation of translation placeholders for localized (da) string component.spook.issues.script_unknown_entity_references.description failed: ({'edit', 'script', 'entities'} != {'edit', 'script', 'entity_id', 'entities'})

and

Logger: homeassistant.helpers.translation
Kilde: helpers/translation.py:276 
Første forekomst: 16.47.59 (1 forekomster) 
Senest logget: 16.47.59

Error while parsing localized (da) string component.spook.issues.group_unknown_members.description
